### ISSUE TITLE
face recognition with webcam

### ISSUE THREAD

**Issue by MohannadBakkar** [justadudewhohacks/face-recognition.js#148]
I am actually lost, I reached the point to use face detector with opencv4nodejs and it works, and I did the face recognition with face-recognition.js and it works perfect, but the problem is how to connect them together? 
I trained the face recognition for my face, but what I missing is how to connect it with a webcam and once I look to the camera I want to tell me that I have this face in my date or I recognize this face. 

What I'm asking for is just a small push or help, and thank you so much.

**Comment by erenaud3** [comment]
Hi @MohannadBakkar !

If you simply want a small help, this is the approach I used : 
-  use opencv4nodejs to get a cv.rect that give you the position of a detected face in your webcam's frame
- enlarge this rect (it will be too small for face recognition otherwise).
- get a cropped image of your frame (to make recognition faster). Something like: 
```
_croppedImage = _frame.getRegion(_enlargedRect);

# (you may need to add .resize(width, height)
```
- convert your image "from opencv4nodejs to face-recognition" 
```
_frFaceImg = fr.cvImageToImageRGB(fr.CvImage(_croppedImage));
```
- recognize face 
```
_faceResults = FaceRecognizer.predictBest(_frFaceImg);
```

As @justadudewhohacks pointed out in README, you could alternatively use face-api.js, which is newer, faster and more browser-friendly (but probably less "back-end friendly").

**Comment by MohannadBakkar** [comment]
@erenaud3 Thank you for your help.

also, I am actually not using any kind of front end, it's only back-end, that's why I didn't choose face-api.js.

**Comment by erenaud3** [comment]
You welcome !

About face-api.js, I think you should consider give it a try. You will see it is really more efficient.
Even if it's clearly front-end oriented (at least when you look at example), you can also use it in back-end using tensors (from tensorflow).

You can find the code I used [here](https://github.com/justadudewhohacks/face-api.js/issues/205) to perform face detection on a webcam feed. (using opencv4nodejs to get webcam frames). You could easily add face recognition. Just do not forget to dispose your tensor, like I did !

**Comment by MohannadBakkar** [comment]
It's interesting, but I do have another question for you @erenaud3.
I want to build a smart lock, so it's only open with face recognition and location, I'm not worried about the board or the hardware because it's nothing, but in the future I want to make it a mobile app, should start right now with face-api.js, or keep going now for what I am doing and leave it to the future? 

Thank you so much for your help

**Comment by MohannadBakkar** [comment]
What do you mean dispose of the tensor? 

Now I'm facing a lot of lagging when I run the face recognizer on the webcam, I have 16 GB of ram btw.
