### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by bobmoff** [justadudewhohacks/face-recognition.js#24]
Hi again, sorry for bothering you with these questions :)

I was just wondering if it is normal to get 800-1000ms when calling locateFaces on an image downsized to 500px height. It just seems a lot to me having seen live face detections on video cameras. I am on a MacBook Pro (Retina, Mid 2012).

Any idea if this is normal or it I might be having some issue that slows down the performance ?

**Comment by justadudewhohacks** [comment]
Yep it's normal, since forward passing an image through the neural net for face detection comes with some certain computational expenses. One has to make a tradeoff between accuracy and performance. You can use opencv4nodejs for face detection, which uses haar cascades instead of a neural net, which will easily give you realtime performance, with a few milliseconds of detection time. However this will not be as stable as the FaceDetector from this package (although the default cascades work quite well with frontal faces).

If you want to get realtime performance with a neural net, mostly people run with a special hardware setup comprising one or multiple NVIDIA gpus. You could as well get you a good NVIDIA gpu and build dlib with cuda. Not sure what performance you can get out of this, since I do not own a cuda compatible gpu either.

**Comment by bobmoff** [comment]
Ok. Thanks again for very fast and great answers.

**Comment by bobmoff** [comment]
Ok. I am back :)

I have now tried a couple of different environments. Initially I was just planning to setup a droplet on Digital Ocean to host the face recognition service and that would be it, but when I got it up and tested it the detection took 15-25 seconds. So I tried some of their more expensive droplets, but with pretty tiny improvments in the results. Then I thought it was because the VPS doesnt even have a GPU at all, so I tried it on a AWS Windows 2018 machine with their new elastic GPU system. After lots of hassle to get it compiling I ended up with the same result. I was confused and made a last try on my gaming machine that is a very high performance desktop computer with Nvidia GTX 1080, and to my suprise, it only dropped to 12 seconds for a detection. I am now really confused as why I get the best performance on my Macbook Pro from 2012.

Looking at the Task Manager on my gaming machine, it doesn't even seem to use the GPU when detecting, and the CPU is up to 17%, but that makes sense as it is probably only usig a single core/logical processor.

You have any idea whats going on ? Whats so unique about my magic super dev machine ? :)

**Comment by justadudewhohacks** [comment]
The performance of the FaceDetector will probably mostly depend on the single core CPU performance e.g. clock rate of a single core. So 10-12 seconds for a 1000x1000 image seems legit I guess. What's the performance of you Macbook for a 1000x1000 image and whats the GHz of a single core?

In order to use a NVIDIA gpu you have to compile dlib with cudasupport, or did you do that? Unfortunately I never tried that as I don't own a cuda compatible gpu. Probably best to ask in the dlib repo for help, if it's not working.

Other than that, if you do not necessarely need such accurate face detection results, you could also try the FrontalFaceDetector from this package, or the face detectors provided by opencv4nodejs, which performs a HAAR based face detection algorithm, instead of using a dnn. This can give you realtime performance. This package can be used together with opencv4nodejs.

**Comment by bobmoff** [comment]
I researched a bit more and noticed that it was only on my mac that it found the BLAS/LAPACK. When building on ubuntu it actually displays a very visual message about this (which i didn't know to look for) that explains that this is missing and how to install the OpenBLAS package using apt-get. I did, and huzzah, the detection speed went down to the same as on my dev machine.

Now I got interested in trying to set this up as a cloud function, to have it parallelized. Either lambda, Google, Azure or something else. Lamba has a limit of 50mb for the full package, and only the shape_predictor_68_face_landmarks.dat is 100mb hehe. Do you know if this file is really needed to just do the face detection, and face recognition ?

Well, thanks again for helping out.

**Comment by justadudewhohacks** [comment]
Nice. I wasn't aware that BLAS and LAPACK accelerate the dnn stuff from dlib. I actually compiled dlib without BLAS and LAPACK, thanks for the tip, will have to try that out. :D 

The 68 point face landmarks vector is used by the face recognizer. Maybe you can only do face detection with Lambda and run face recognition on some other service. I think the recognition step is much faster anyways, compared to the detector.
