### ISSUE TITLE
typescript defentitions

### ISSUE THREAD

**Issue by HackPoint** [justadudewhohacks/face-recognition.js#35]
Please add @types/face-recognition if you need API for this. I can write it to you.

**Comment by justadudewhohacks** [comment]
@ksachdeva is currently working on typescript definitions, which is highly appreciated.

**Comment by ksachdeva** [comment]
Hi @HackPoint ,

There is an example project called "typed"  written in typescript which essentially duplicates the examples. You can use that to see the usage of the definitions

Regards
Kapil

**Comment by m-onz** [comment]
Would be nice not to impose typescript on people though.

**Comment by ksachdeva** [comment]
It is not imposed. The library is written using javascript. What you get as part of npm install is a file called index.d.ts which vs-code uses to provide intellisense for both typescript and javascript projects.

That being said, even if the project was written using typescript what you would have obtained from npm would be the javascript files.

**Comment by m-onz** [comment]
That is all correct... my point is that using typescript assumes you want to add types to JavaScript... as a javascript developer I don't care about types and I don't like working with typescript. Typescript is an opinioned choice which is why I said "imposed".

Regardless of whether it arrives as Javascript I don't excessive build chains... do we need gulp too?

**Comment by justadudewhohacks** [comment]
Not sure if i understood correctly. You can still use the package without typescript. Only a typings file has been added so that one can use this module properly with typescript if wanted.

**Comment by m-onz** [comment]
Indeed. Ignore me! I just dislike typescript a lot.
